# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tornado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeX', models.IntegerField(blank=True, default=3)),
                ('sizeY', models.IntegerField(blank=True, default=3)),
                ('status', models.CharField(choices=[(b'IN_PROGRESS', b'In progress'), (b'DRAW', b'Draw'), (b'WINNER', b'Winner')], max_length=64)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privatemessages_game_turn', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privatemessages_game_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('num', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tornado.Game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
