# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornado', '0002_game_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default=b'Game', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(b'OPEN', b'Open'), (b'IN_PROGRESS', b'In progress'), (b'DRAW', b'Draw'), (b'WINNER', b'Winner')], default=b'IN_PROGRESS', max_length=64),
        ),
    ]
