# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=b'Game', max_length=32)),
                ('sizeX', models.IntegerField(blank=True, default=3)),
                ('sizeY', models.IntegerField(blank=True, default=3)),
                ('combo', models.IntegerField(blank=True, default=3)),
                ('liniar_rool', models.BooleanField(default=True, verbose_name=b'Liniar rool')),
                ('diagonal_rool', models.BooleanField(default=True, verbose_name=b'Diagonal rool')),
                ('status', models.CharField(choices=[(b'OPEN', b'Open'), (b'START', b'Start'), (b'IN_PROGRESS', b'In progress'), (b'DRAW', b'Draw'), (b'WINNER', b'Winner')], default=b'OPEN', max_length=64)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_tack_toe_game_first', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_tack_toe_game_turn', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tick_tack_toe_game_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tick_tack_toe.Game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
