# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_tack_toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='combo',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(b'OPEN', b'Open'), (b'START', b'Start'), (b'IN_PROGRESS', b'In progress'), (b'DRAW', b'Draw'), (b'WINNER', b'Winner')], default=b'OPEN', max_length=64),
        ),
    ]
