# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tick_tack_toe', '0003_auto_20160614_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='diagonal_rool',
            field=models.BooleanField(default=True, verbose_name=b'Diagonal rool'),
        ),
        migrations.AddField(
            model_name='game',
            name='liniar_rool',
            field=models.BooleanField(default=True, verbose_name=b'Liniar rool'),
        ),
    ]
