# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tick_tack_toe', '0004_auto_20160614_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='num',
        ),
    ]
